name: Test Go

on:
  push:
    branches:
      - main
    paths:
      - server/**
  pull_request:
    paths:
      - server/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: make test-go
